version: "3.8"

services:
    app:
        container_name: project1
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODOS_DB_HOSTNAME: ${NODOS_DB_HOSTNAME}
            NODOS_DB_USERNAME: ${NODOS_DB_USERNAME}
            NODOS_DB_PASSWORD: ${NODOS_DB_PASSWORD}
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        command: nodos server -h 0.0.0.0
