version: "3.8"

services:
    app:
        container_name: project1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        command: nodos server -h 0.0.0.0
        depends_on:
            - db

    caddy:
        image: caddy:2.3.0-alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - app

    db:
        image: ${NODOS_DB_TYPE}:latest
        container_name: db
        environment:
            POSTGRES_USER: ${NODOS_DB_USERNAME}
            POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
            POSTGRES_DB: ${NODOS_DB_HOSTNAME}

volumes:
    caddy_data:
    caddy_config:
