name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODOS_DB_HOSTNAME: localhost
      NODOS_DB_USERNAME: postgres
      NODOS_DB_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2

      - name: Run test
        run: npm test
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ott45/devops-for-programmers-project-lvl1:latest
