name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODOS_DB_HOSTNAME: ${{ secrets.NODOS_DB_HOSTNAME }}
      NODOS_DB_USERNAME: ${{ secrets.NODOS_DB_USERNAME }}
      NODOS_DB_PASSWORD: ${{ secrets.NODOS_DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Npm install
        run: npm install

      - name: Run test
        run: npm test
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ott45/devops-for-programmers-project-lvl1:latest
